### PR TITLE
Issue #85: 🐛  Fix bug that prevents childMarkdownRemark from being set

### LINKED ISSUE #85: Empty link causes build error in gatsby develop
- `gatsby-remark-embedder` version: 1.11.1
- `node` version: 12.14.1
- `npm` (or `yarn`) version: 6.13.4

Relevant code or config

```
[](https://example.com)
```

What you did:

We had a markdown file that had a weird link formatted like `[](https://example.com)`. The text portion of the link was empty.

What happened:

When the graphQL query was run on that file we got an error.

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "htmlAst" on type "MarkdownRemark".

GraphQL request:9:9
 8 |       childMarkdownRemark {
 9 |         htmlAst
   |         ^
10 |         tableOfContents

File: src/templates/markdownTemplate.js:92:9
```

Basically everything under `childMarkdownRemark` was null.

Reproduction repository:

Just add a link like `[](https://example.com)` to any markdown document in a gatsby project that uses this plugin and you'll be able to reproduce this error. 

Problem description:

See above.

Suggested solution:

PR coming in a minute.

### PR DESCRIPTION
**Pull request by macdonst**
**What**:
Closes #85 

**Why**:
If the change isn't made there is a particular link format that can keep the entire markdown document from being rendered.

**How**:
Added an extra check in the isValid link code.

**Checklist**:
- [N/A] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

File: src/__tests__/__fixtures__/kitchensink.md [hunk 1]
```diff
@@ -4,8 +4,7 @@
 
 This is a normal paragraph.
 
-This is the first line of a multi-line paragraph.  
-And this is the second line.
+This is the first line of a multi-line paragraph. And this is the second line.
```
Comment (MichaelDeBoey) [inline src/__tests__/__fixtures__/kitchensink.md]: Revert this one

```suggestion
This is the first line of a multi-line paragraph.  
And this is the second line.
```

File: src/__tests__/plugin.js [hunk 2]
```diff
@@ -30,7 +30,7 @@ describe('gatsby-remark-embedder', () => {
 
       This is a normal paragraph.
 
-      This is the first line of a multi-line paragraph.  
+      This is the first line of a multi-line paragraph.
```
Comment (MichaelDeBoey) [inline src/__tests__/plugin.js]: Same

```suggestion
      This is the first line of a multi-line paragraph.  
```

File: src/__tests__/plugin.js [hunk 3]
```diff
@@ -65,4 +65,21 @@ describe('gatsby-remark-embedder', () => {
       "
     `);
   });
+
+  test('can transform a link with no label (emptylink)', async () => {
```
Comment (MichaelDeBoey) [inline src/__tests__/plugin.js]: We don't need an extra test, because we can just use the kitchensink test instead

File: src/__tests__/__fixtures__/emptylink.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+# Heading 1
+
+## Heading2
+
+This is a normal paragraph.
+
+[](https://example.com)
```
Comment (MichaelDeBoey) [inline src/__tests__/__fixtures__/emptylink.md]: Just put this in the kitchensink fixture

File: src/index.js [hunk 5]
```diff
@@ -31,6 +31,7 @@ export default async (
     const isValidLink =
       node.type === 'link' &&
       node.title === null &&
+      node.children[0] &&
```
Comment (MichaelDeBoey) [inline src/index.js]: I think this makes it a bit clearer

```suggestion
      node.children.length === 1 &&
```

**Comment by macdonst** [comment]
@MichaelDeBoey I'll update the PR. Looks like Prettier decided to mess with all the whitespace.

File: src/index.js (hunk 5 above)
Comment (macdonst) [reply src/index.js]: done

**Comment by macdonst** [comment]
@MichaelDeBoey PR updates with your requested changes.

**Comment by MichaelDeBoey** [comment]
Going to close this for the reason explained in the issue (https://github.com/MichaelDeBoey/gatsby-remark-embedder/issues/85#issuecomment-583326814):

> @macdonst I've had some thoughts about this and I'm going to close this issue + the accompanied PR, since the use of a link without a child text will never happen in real projects.
> 
> If you want to create a visual delimiter you can always use an HTML comment like
> ```html
> 
> ```

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @macdonst for code and tests
